name: kilometrosycentimos
description: Una aplicación Flutter para gestionar tus coches, kilómetros y gastos.
publish_to: 'none' # si no lo publicarás en pub.dev

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.2.1
  http: ^1.5.0
  image_picker: ^1.1.2
  supabase_flutter: ^2.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
